# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb594e057089e665b1e6a21ae322a6a74ef5c0f4c2ecd86c0b12e758006dc8c6a808efe1a6d31a848a5cb849a4f01d249577cc45b5573e5f734c38148708460f

test:
  secret_key_base: 2fad2c18b48a638646a176794fe36dcc781181fea8056e2e858b46f5249ef09f0c29fd9df533ae14a6a4182833af5c1eaa5e2ae991373989b3f96c629d030f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
